suffixInList: false
chatseparator: "&8>>"
Groups:
  Admin:
    prefix: "&b[&4Administrateur&b] "
    suffix: ""
    color: "&b"
    permissions:
      - minecraft.command.op
  Default:
    prefix: "&b[&eBakuscien&b]&e "
    suffix: ""
    color: "&e"
    permissions:
      - none
