suffixInList: false
chatseparator: "&8>> "
Groups:
  ADMIN:
    prefix: "&b[&4Administrateur&b]"
    suffix: ""
    color: "&b"
    tabPriority: 1
    name: "Administrateur"
    permissions:
      - minecraft.command.op
  DEFAULT:
    prefix: "&b[&eJoueur&b]&e"
    suffix: ""
    color: "&e"
    tabPriority: 11
    name: "Joueur"
    permissions:
      - none
